apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: bjitpdmad/api-gateway-service:latest
          ports:
            - containerPort: 9490
          env:
            - name: SERVER_PORT
              value: "9490"
            - name: SPRING_APPLICATION_NAME
              value: ApiGateway
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
              value: "true"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID
              value: "true"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY
              value: DEBUG
            - name: LOGGING_LEVEL_REACTOR_NETTY_HTTP_CLIENT
              value: DEBUG
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"