apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: bjitpdmad/notification-service:latest
          ports:
            - containerPort: 9496
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/user-service-db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: secure_password_2025
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: SPRING_APPLICATION_NAME
              value: notification-service
            - name: SERVER_PORT
              value: "9496"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect